[build]
  command = "gatsby build"
  functions = "api/"
  publish = "public"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[functions]
  directory = "api"
  # Includes all Markdown files inside the "files/" directory.
  included_files = ["api/"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200