[build]
  command = "gatsby build"
  functions = "netlify/functions"
  publish = "public"

[[plugins]]
  package = "@netlify/plugin-gatsby"
  package = "plugins.inputs.postBuild"
  package = "plugins.inputs"
